# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(518, 270)
        MainWindow.setMinimumSize(QtCore.QSize(518, 270))
        MainWindow.setMaximumSize(QtCore.QSize(518, 270))
        self.userinterface = QtWidgets.QWidget(MainWindow)
        self.userinterface.setObjectName("userinterface")
        self.gridLayout = QtWidgets.QGridLayout(self.userinterface)
        self.gridLayout.setObjectName("gridLayout")
        self.block_response = QtWidgets.QGridLayout()
        self.block_response.setObjectName("block_response")
        self.response_savetofile = QtWidgets.QPushButton(self.userinterface)
        self.response_savetofile.setEnabled(False)
        self.response_savetofile.setObjectName("response_savetofile")
        self.block_response.addWidget(self.response_savetofile, 1, 1, 1, 1)
        self.response_shell = QtWidgets.QTextEdit(self.userinterface)
        self.response_shell.setReadOnly(True)
        self.response_shell.setObjectName("response_shell")
        self.block_response.addWidget(self.response_shell, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.block_response, 0, 4, 1, 1)
        self.block_setting = QtWidgets.QFormLayout()
        self.block_setting.setObjectName("block_setting")
        self.ctdiskurl_label = QtWidgets.QLabel(self.userinterface)
        self.ctdiskurl_label.setEnabled(True)
        self.ctdiskurl_label.setObjectName("ctdiskurl_label")
        self.block_setting.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ctdiskurl_label)
        self.ctdiskurl_value = QtWidgets.QLineEdit(self.userinterface)
        self.ctdiskurl_value.setObjectName("ctdiskurl_value")
        self.block_setting.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ctdiskurl_value)
        self.button_analyze = QtWidgets.QPushButton(self.userinterface)
        self.button_analyze.setObjectName("button_analyze")
        self.block_setting.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.button_analyze)
        self.destination_label = QtWidgets.QLabel(self.userinterface)
        self.destination_label.setObjectName("destination_label")
        self.block_setting.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.destination_label)
        self.destination_value_container = QtWidgets.QHBoxLayout()
        self.destination_value_container.setObjectName("destination_value_container")
        self.destination_value = QtWidgets.QLineEdit(self.userinterface)
        self.destination_value.setEnabled(False)
        self.destination_value.setReadOnly(True)
        self.destination_value.setObjectName("destination_value")
        self.destination_value_container.addWidget(self.destination_value)
        self.destination_value_choosedir = QtWidgets.QToolButton(self.userinterface)
        self.destination_value_choosedir.setEnabled(False)
        self.destination_value_choosedir.setObjectName("destination_value_choosedir")
        self.destination_value_container.addWidget(self.destination_value_choosedir)
        self.block_setting.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.destination_value_container)
        self.itemnum_label = QtWidgets.QLabel(self.userinterface)
        self.itemnum_label.setObjectName("itemnum_label")
        self.block_setting.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.itemnum_label)
        self.itemnum_value_container = QtWidgets.QHBoxLayout()
        self.itemnum_value_container.setObjectName("itemnum_value_container")
        self.itemnum_value_first = QtWidgets.QSpinBox(self.userinterface)
        self.itemnum_value_first.setEnabled(False)
        self.itemnum_value_first.setMinimum(1)
        self.itemnum_value_first.setObjectName("itemnum_value_first")
        self.itemnum_value_container.addWidget(self.itemnum_value_first)
        self.itemnum_value_separator = QtWidgets.QLabel(self.userinterface)
        self.itemnum_value_separator.setAlignment(QtCore.Qt.AlignCenter)
        self.itemnum_value_separator.setObjectName("itemnum_value_separator")
        self.itemnum_value_container.addWidget(self.itemnum_value_separator)
        self.itemnum_value_last = QtWidgets.QSpinBox(self.userinterface)
        self.itemnum_value_last.setEnabled(False)
        self.itemnum_value_last.setMinimum(1)
        self.itemnum_value_last.setObjectName("itemnum_value_last")
        self.itemnum_value_container.addWidget(self.itemnum_value_last)
        self.block_setting.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.itemnum_value_container)
        self.timeout_label = QtWidgets.QLabel(self.userinterface)
        self.timeout_label.setObjectName("timeout_label")
        self.block_setting.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.timeout_label)
        self.timeout_value = QtWidgets.QSpinBox(self.userinterface)
        self.timeout_value.setEnabled(False)
        self.timeout_value.setMinimum(100)
        self.timeout_value.setMaximum(3600)
        self.timeout_value.setSingleStep(30)
        self.timeout_value.setProperty("value", 300)
        self.timeout_value.setObjectName("timeout_value")
        self.block_setting.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.timeout_value)
        self.button_download = QtWidgets.QPushButton(self.userinterface)
        self.button_download.setEnabled(False)
        self.button_download.setObjectName("button_download")
        self.block_setting.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.button_download)
        self.gridLayout.addLayout(self.block_setting, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.userinterface)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ctdiskautodl"))
        self.response_savetofile.setText(_translate("MainWindow", "SAVE TO FILE"))
        self.ctdiskurl_label.setText(_translate("MainWindow", "CTDISK URL"))
        self.button_analyze.setText(_translate("MainWindow", "Analyze"))
        self.destination_label.setText(_translate("MainWindow", "Destination"))
        self.destination_value_choosedir.setText(_translate("MainWindow", "..."))
        self.itemnum_label.setText(_translate("MainWindow", "Item #"))
        self.itemnum_value_separator.setText(_translate("MainWindow", "-"))
        self.timeout_label.setText(_translate("MainWindow", "Timeout"))
        self.button_download.setText(_translate("MainWindow", "Download!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
